# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: m.dudarev2002@gmail.com
author_name: buenajen
has_binder: true
has_settings: true
kind: server
labextension_name: md_html_preview
project_short_description: A JupyterLab extension for render md to html
python_name: md_html_preview
repository: https://github.com/buenajen/md_html_preview
test: true

